# Generated by Django 4.0 on 2021-12-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(choices=[('o_positive', 'O+'), ('a_positive', 'A+'), ('o_negative', 'O-'), ('b_positive', 'B+'), ('a_negative', 'A-'), ('ab_positive', 'AB+'), ('b_negative', 'B-'), ('ab_negative', 'AB-')], max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Prefer not to say')], max_length=20)),
                ('email', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
