# Generated by Django 4.0 on 2021-12-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_management_system', '0002_delete_users_remove_donors_password_donors_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O+'), ('A+', 'A+'), ('O-', 'O-'), ('B+', 'B+'), ('A-', 'A-'), ('AB+', 'AB+'), ('B-', 'B-'), ('AB-', 'AB-')], max_length=30, null=True),
        ),
    ]
