# Generated by Django 4.0 on 2021-12-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_management_system', '0003_alter_donors_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
