# Generated by Django 4.0 on 2021-12-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_management_system', '0006_donors_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='username',
        ),
    ]
